spring.application.name=sbschoolmanager-api
# src/main/resources/application.properties
# Perfil activo por defecto ? cambia a 'docker' cuando uses Docker
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect DESACTUALIZADO
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect